Removed -L/usr/lib from SSL search path.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2921,11 +2921,69 @@ EOF
 
 fi
 
-    echo "$as_me:2924: checking for ssl" >&5
+echo "$as_me:2924: checking for SSL_accept in -lssl" >&5
+echo $ECHO_N "checking for SSL_accept in -lssl... $ECHO_C" >&6
+if test "${ac_cv_lib_ssl_SSL_accept+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lssl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line 2932 "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SSL_accept ();
+int
+main ()
+{
+SSL_accept ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:2951: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:2954: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:2957: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:2960: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ssl_SSL_accept=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_ssl_SSL_accept=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:2971: result: $ac_cv_lib_ssl_SSL_accept" >&5
+echo "${ECHO_T}$ac_cv_lib_ssl_SSL_accept" >&6
+if test $ac_cv_lib_ssl_SSL_accept = yes; then
+  cat >>confdefs.h <<EOF
+#define HAVE_LIBSSL 1
+EOF
+
+  LIBS="-lssl $LIBS"
+
+else
+
+    echo "$as_me:2982: checking for ssl" >&5
 echo $ECHO_N "checking for ssl... $ECHO_C" >&6
     ssldirs="/usr/local/openssl /usr/lib/openssl /usr/openssl \
 	    /usr/local/ssl /usr/lib/ssl /usr/ssl \
-	    /usr/pkg /usr/local /usr"
+	    /usr/pkg /usr/local"
 
 # Check whether --with-ssl or --without-ssl was given.
 if test "${with_ssl+set}" = set; then
@@ -2946,7 +3004,7 @@ fi;
 	fi
     done
     if test x_$found_ssl != x_yes; then
-	{ { echo "$as_me:2949: error: cannot find ssl libraries" >&5
+	{ { echo "$as_me:3007: error: cannot find ssl libraries" >&5
 echo "$as_me: error: cannot find ssl libraries" >&2;}
    { (exit 1); exit 1; }; }
     else
@@ -2957,10 +3015,169 @@ echo "$as_me: error: cannot find ssl libraries" >&2;}
 	HAVE_SSL=yes
     fi
 
-    echo "$as_me:2960: result: yes" >&5
+    echo "$as_me:3018: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
-    echo "$as_me:2963: checking for pam" >&5
+fi
+
+echo "$as_me:3023: checking for SSLeay_version in -lcrypto" >&5
+echo $ECHO_N "checking for SSLeay_version in -lcrypto... $ECHO_C" >&6
+if test "${ac_cv_lib_crypto_SSLeay_version+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcrypto  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line 3031 "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SSLeay_version ();
+int
+main ()
+{
+SSLeay_version ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:3050: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:3053: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:3056: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:3059: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_crypto_SSLeay_version=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_crypto_SSLeay_version=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:3070: result: $ac_cv_lib_crypto_SSLeay_version" >&5
+echo "${ECHO_T}$ac_cv_lib_crypto_SSLeay_version" >&6
+if test $ac_cv_lib_crypto_SSLeay_version = yes; then
+  cat >>confdefs.h <<EOF
+#define HAVE_LIBCRYPTO 1
+EOF
+
+  LIBS="-lcrypto $LIBS"
+
+else
+
+    echo "$as_me:3081: checking for ssl" >&5
+echo $ECHO_N "checking for ssl... $ECHO_C" >&6
+    ssldirs="/usr/local/openssl /usr/lib/openssl /usr/openssl \
+	    /usr/local/ssl /usr/lib/ssl /usr/ssl \
+	    /usr/pkg /usr/local"
+
+# Check whether --with-ssl or --without-ssl was given.
+if test "${with_ssl+set}" = set; then
+  withval="$with_ssl"
+  ssldirs="$withval"
+fi;
+    for dir in $ssldirs; do
+	ssldir="$dir"
+	if test -f "$dir/include/openssl/ssl.h"; then
+	    found_ssl="yes";
+	    CPPFLAGS="$CPPFLAGS -I$ssldir/include";
+	    break;
+	fi
+	if test -f "$dir/include/ssl.h"; then
+	    found_ssl="yes";
+	    CPPFLAGS="$CPPFLAGS -I$ssldir/include";
+	    break
+	fi
+    done
+    if test x_$found_ssl != x_yes; then
+	{ { echo "$as_me:3106: error: cannot find ssl libraries" >&5
+echo "$as_me: error: cannot find ssl libraries" >&2;}
+   { (exit 1); exit 1; }; }
+    else
+	TLSDEFS=-DTLS;
+
+	LIBS="$LIBS -lssl -lcrypto";
+	LDFLAGS="$LDFLAGS -L$ssldir/lib";
+	HAVE_SSL=yes
+    fi
+
+    echo "$as_me:3117: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+fi
+
+echo "$as_me:3122: checking for pam_start in -lpam" >&5
+echo $ECHO_N "checking for pam_start in -lpam... $ECHO_C" >&6
+if test "${ac_cv_lib_pam_pam_start+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpam  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line 3130 "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char pam_start ();
+int
+main ()
+{
+pam_start ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:3149: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:3152: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:3155: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:3158: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_pam_pam_start=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_pam_pam_start=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:3169: result: $ac_cv_lib_pam_pam_start" >&5
+echo "${ECHO_T}$ac_cv_lib_pam_pam_start" >&6
+if test $ac_cv_lib_pam_pam_start = yes; then
+  cat >>confdefs.h <<EOF
+#define HAVE_LIBPAM 1
+EOF
+
+  LIBS="-lpam $LIBS"
+
+else
+
+    echo "$as_me:3180: checking for pam" >&5
 echo $ECHO_N "checking for pam... $ECHO_C" >&6
     pamdirs="/usr/local /usr"
 
@@ -2986,7 +3203,7 @@ fi;
 	HAVE_PAM=no
 	PAMLIBS=;
 
-	echo "$as_me:2989: result: no" >&5
+	echo "$as_me:3206: result: no" >&5
 echo "${ECHO_T}no" >&6
     else
 	PAMDEFS=-DPAM;
@@ -2995,11 +3212,13 @@ echo "${ECHO_T}no" >&6
 
 	HAVE_PAM=yes
 
-	echo "$as_me:2998: result: yes" >&5
+	echo "$as_me:3215: result: yes" >&5
 echo "${ECHO_T}yes" >&6
     fi
 
-    echo "$as_me:3002: checking for zeroconf" >&5
+fi
+
+    echo "$as_me:3221: checking for zeroconf" >&5
 echo $ECHO_N "checking for zeroconf... $ECHO_C" >&6
     zeroconfdirs="/usr /usr/local"
 
@@ -3018,14 +3237,14 @@ fi;
     done
     if test x_$found_zeroconf != x_yes; then
 	HAVE_ZEROCONF=no
-	echo "$as_me:3021: result: no" >&5
+	echo "$as_me:3240: result: no" >&5
 echo "${ECHO_T}no" >&6
     else
 	ZEROCONFDEFS=-DZEROCONF;
 
 	HAVE_ZEROCONF=yes
 
-	echo "$as_me:3028: result: yes" >&5
+	echo "$as_me:3247: result: yes" >&5
 echo "${ECHO_T}yes" >&6
     fi
 
@@ -3117,7 +3336,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:3120: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:3339: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -3290,7 +3509,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:3293: error: ambiguous option: $1
+    { { echo "$as_me:3512: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3309,7 +3528,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:3312: error: unrecognized option: $1
+  -*) { { echo "$as_me:3531: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3346,7 +3565,7 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:3349: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3568: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3567,7 +3786,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3570: creating $ac_file" >&5
+    { echo "$as_me:3789: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3585,7 +3804,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3588: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3807: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3598,7 +3817,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3601: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3820: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3659,7 +3878,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:3662: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:3881: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -3670,7 +3889,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3673: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3892: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3683,7 +3902,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3686: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3905: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3800,7 +4019,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:3803: $ac_file is unchanged" >&5
+      { echo "$as_me:4022: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -3904,7 +4123,7 @@ if test "$no_recursion" != yes; then
     # parts of a large source tree are present.
     test -d $srcdir/$ac_subdir || continue
 
-    { echo "$as_me:3907: configuring in $ac_subdir" >&5
+    { echo "$as_me:4126: configuring in $ac_subdir" >&5
 echo "$as_me: configuring in $ac_subdir" >&6;}
     case $srcdir in
     .) ;;
@@ -3926,7 +4145,7 @@ done; }
 
        if test -d ./$ac_subdir; then :;
        else
-         { { echo "$as_me:3929: error: cannot create \`pwd\`/$ac_subdir" >&5
+         { { echo "$as_me:4148: error: cannot create \`pwd\`/$ac_subdir" >&5
 echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
        fi
@@ -3957,7 +4176,7 @@ echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
     elif test -f $ac_sub_srcdir/configure.in; then
       ac_sub_configure=$ac_configure
     else
-      { echo "$as_me:3960: WARNING: no configuration information is in $ac_subdir" >&5
+      { echo "$as_me:4179: WARNING: no configuration information is in $ac_subdir" >&5
 echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
       ac_sub_configure=
     fi
@@ -3971,12 +4190,12 @@ echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
         ac_sub_cache_file=$ac_dots$cache_file ;;
       esac
 
-      { echo "$as_me:3974: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
+      { echo "$as_me:4193: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
 echo "$as_me: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&6;}
       # The eval makes quoting arguments work.
       eval $ac_sub_configure $ac_sub_configure_args \
            --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir ||
-        { { echo "$as_me:3979: error: $ac_sub_configure failed for $ac_subdir" >&5
+        { { echo "$as_me:4198: error: $ac_sub_configure failed for $ac_subdir" >&5
 echo "$as_me: error: $ac_sub_configure failed for $ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
     fi
